# Generated by Django 5.2 on 2025-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueño', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('fecha_reserva', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
