# Generated by Django 5.2 on 2025-06-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_reserva_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
