# Generated by Django 5.2 on 2025-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reserva_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.CharField(choices=[('peluqueria', 'peluqueria'), ('vacuna', 'vacuna'), ('atencion medica', 'atencion medica')], max_length=50, null=True),
        ),
    ]
